### ISSUE TITLE
Joining forces

### ISSUE THREAD

**Issue by vyorkin** [csicar/purescript-unicode-prelude#2]
Hi, Carsten!

I've came here by googling the `purescript-unicode-prelude` to find the
similar package that I've published a year ago or so (https://github.com/vyorkin/purescript-unicode-prelude). Unfortunately, at that time I haven't noticed that you've done almost the same work earlier, otherwise I'd just send PR's to this repo.

As I can see there are couple of missing operators in my package, e.g. `∃` and `∀`.
Also, I don't have these type aliases:
```
type ℝ = Number
type ℕ = Int
```

I just want to ask if you want to join forces?
If yes, what will be the best way to collaborate further?
Would you mind if I'll just add all the missing pieces I've mentioned above to my package and add you as a collaborator to the repo?

**Comment by csicar** [comment]
It's quite amazing seeing that we created similar packages independently (even the same name). Seems like we are on the right track then ;).

> I just want to ask if you want to join forces?

Yes!

> Would you mind if I'll just add all the missing pieces I've mentioned above to my package and add you as a collaborator to the repo?

I think that would be the right thing to to. I'll deprecate this repo and link to your repo.

**Comment by csicar** [comment]
Licenses also seems compatible (MIT, MIT) so I don't see any problem.

**Comment by vyorkin** [comment]
Thanks! I'll add the missing parts in a minute a publish a new version
